apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.AIServer.name }}
  labels:
    app: {{ .Values.AIServer.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.AIServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.AIServer.name }}
    spec:
      containers:
        - name: {{ .Values.AIServer.name }}
          image: {{ .Values.AIServer.image.name }}:{{ .Values.AIServer.image.tag }}
          imagePullPolicy: {{ .Values.AIServer.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.AIServer.port }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env | quote }}
            # Database Configuration
            - name: MYSQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.AIServer.secrets.name }}
                  key: mysql-host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.AIServer.secrets.name }}
                  key: mysql-port
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.AIServer.secrets.name }}
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.AIServer.secrets.name }}
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.AIServer.secrets.name }}
                  key: mysql-password
            # AI Configuration
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.AIServer.secrets.name }}
                  key: gemini-api-key
          {{- range $key, $value := .Values.AIServer.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.AIServer.name }}
spec:
  selector:
    app: {{ .Values.AIServer.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.AIServer.port }}
      targetPort: {{ .Values.AIServer.targetPort }}
  type: {{ .Values.AIServer.serviceType }}
---

