apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartrent-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
        - scraper.{{ .Values.host }}
{{- if eq .Values.env "dev" }}
        - ai.{{ .Values.host }}
{{- end }}
      secretName: smartrent-tls-{{ .Values.env }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.BEServer.name }}
                port:
                  number: {{ .Values.BEServer.port }}
    - host: scraper.{{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ScraperServer.name }}
                port:
                  number: {{ .Values.ScraperServer.port }}
{{- if eq .Values.env "dev" }}
    - host: ai.{{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.AIServer.name }}
                port:
                  number: {{ .Values.AIServer.port }}
{{- end }}