host: dev.smartrent-api.vuhuydiet.xyz
env: dev
BEServer:
  image:
    tag: 833a0bd11eba6b695c36a1e5829985e8458b23eb
AIServer:
  image:
    tag: dev-3146edd
  env:
    APP_NAME: "SmartRent AI Service"
    VERSION: "1.0.0"
    ENVIRONMENT: "development"
    DEBUG: "true"
ScraperServer:
  image:
    tag: dev-d2f0522
  env:
    NODE_ENV: "development"
    PORT: "3000"
    LOG_LEVEL: "debug"
    DEBUG: "true"
